name: Rust Example
on:
  push:
    branches:
      - master

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Rust benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup toolchain update nightly && rustup default nightly
      - name: Run benchmark
        run: cargo bench | tee output.txt

      - name: Continuous Benchmark
        uses: benchmark-action/github-action-benchmark@v1.16.2

        with:
          name: Rust Benchmark
          tool: 'cargo'
          output-file-path: benchmarks/output.txt
